name: Debug macOS GraalPy

on:
  workflow_dispatch:
    inputs:
      graalpython_run_id:
        type: string
        description: Run id from timfel/graalpython's Debug macOS GraalPy Artifact workflow
        required: true
      graalpython_repo:
        type: string
        description: Repository containing the GraalPy artifact
        default: timfel/graalpython
        required: true
      graalpy_artifact:
        type: choice
        description: GraalPy artifact to test
        default: graalpy-macos-amd64
        options:
          - graalpy-macos-amd64
          - graalpy-macos-aarch64

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ${{ inputs.graalpy_artifact == 'graalpy-macos-amd64' && 'macos-13' || 'macos-15' }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - uses: actions/download-artifact@v5
        with:
          repository: ${{ inputs.graalpython_repo }}
          run-id: ${{ inputs.graalpython_run_id }}
          name: ${{ inputs.graalpy_artifact }}
          path: graalpy-artifact
          github-token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --no-dev --group test

      - name: Generate a sample project
        run: uv run --no-sync -m test.test_projects test.test_0_basic.basic_project sample_proj

      - name: Build GraalPy wheel with downloaded artifact
        uses: ./
        with:
          package-dir: sample_proj
          output-dir: wheelhouse
        env:
          CIBW_ENABLE: graalpy
          CIBW_BUILD: gp312_250-*
          CIBW_ARCHS_MACOS: ${{ inputs.graalpy_artifact == 'graalpy-macos-amd64' && 'x86_64' || 'arm64' }}
          CIBW_GRAALPY_MACOS_AMD64_URL: file://${{ github.workspace }}/graalpy-artifact/graalpy-debug-macos-amd64.tar.gz
          CIBW_GRAALPY_MACOS_AARCH64_URL: file://${{ github.workspace }}/graalpy-artifact/graalpy-debug-macos-aarch64.tar.gz
          PIP_PROGRESS_BAR: "off"

      - uses: actions/upload-artifact@v4
        with:
          name: cibuildwheel-graalpy-${{ inputs.graalpy_artifact }}
          path: wheelhouse/*.whl
